loki:
  auth_enabled: false # todo: add auth
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  pattern_ingester:
    enabled: true
  limits_config:
    retention_period: 48h
    allow_structured_metadata: true
    volume_enabled: true
  ruler:
    enable_api: true
  compactor:
    working_directory: /var/loki/compactor
    compaction_interval: 5m
    retention_enabled: true
    retention_delete_delay: 2h
    retention_delete_worker_count: 150
    delete_request_store: s3

minio:
  enabled: true
  persistence:
    size: 25Gi
    storageClass: local-path
  securityContext:
    enabled: true
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault
  initContainers:
    - name: fix-permissions
      image: busybox:1.35
      command:
        ["sh", "-c", "chmod -R 755 /export && chown -R 1001:1001 /export"]
      volumeMounts:
        - name: export
          mountPath: /export
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        allowPrivilegeEscalation: false
        capabilities:
          add: ["CHOWN", "FOWNER"]
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault

deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    storageClass: local-path
    size: 10Gi
  securityContext:
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault
  initContainers:
    - name: fix-permissions
      image: busybox:1.35
      command:
        ["sh", "-c", "chmod -R 755 /var/loki && chown -R 10001:10001 /var/loki"]
      volumeMounts:
        - name: storage
          mountPath: /var/loki
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        allowPrivilegeEscalation: false
        capabilities:
          add: ["CHOWN", "FOWNER"]
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault

compactor:
  enabled: true

# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0

# Reduce memory usage for homelab environment
chunksCache:
  replicas: 1
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi

resultsCache:
  replicas: 1
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi
