apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/rancher/local-path-provisioner/deploy?ref=v0.0.26
patches:
  - patch: |-
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: local-path-config
        namespace: local-path-storage
      data:
        config.json: |-
          {
                  "nodePathMap":[
                  {
                          "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                          "paths":["/var/local-path-provisioner"]
                  }
                  ]
          }
        setup: |-
          #!/bin/sh
          set -eu
          mkdir -p "$VOL_DIR"
          # Make directory world-writable initially so any non-root user can access
          chmod 777 "$VOL_DIR"
          # The application's initContainer or fsGroup will handle final ownership
        teardown: |-
          #!/bin/sh
          set -eu
          rm -rf "$VOL_DIR"
  - patch: |-
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: local-path
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: local-path-storage
        labels:
          pod-security.kubernetes.io/enforce: privileged
