repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: tailscale
    url: https://pkgs.tailscale.com/helmcharts

releases:
  - name: ingress-nginx
    namespace: ingress
    createNamespace: true
    chart: ingress-nginx/ingress-nginx
    wait: true
    timeout: 300
    values:
      - ./values/ingress-nginx/base.yaml
      - ./security.yaml

  - name: grafana
    namespace: monitoring
    createNamespace: true
    chart: grafana/grafana
    values:
      - ./values/grafana/base.yaml
      - ./security.yaml

  - name: loki
    namespace: monitoring
    chart: grafana/loki
    values:
      - ./values/loki/base.yaml
      - ./security.yaml

  - name: alloy
    namespace: monitoring
    chart: grafana/alloy
    wait: true
    timeout: 300
    values:
      - ./values/alloy/base.yaml
      - ./security.yaml

  - name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    wait: true
    timeout: 600
    values:
      - ./values/kube-prometheus-stack/base.yaml

  - name: tailscale-operator
    namespace: tailscale
    createNamespace: true
    chart: tailscale/tailscale-operator
    version: 1.86.5
    wait: true
    timeout: 300
    values:
      - ./values/tailscale-operator/base.yaml
    # After install/upgrade, apply (or re-apply) the Connector CR to ensure exit node exists.
    hooks:
      # Ensure namespace allows privileged pods required for exit node functionality (sysctls & NET_ADMIN capabilities).
      - events: [preSync]
        command: kubectl
        showlogs: true
        args:
          - label
          - namespace
          - tailscale
          - pod-security.kubernetes.io/enforce=privileged
          - pod-security.kubernetes.io/audit=privileged
          - pod-security.kubernetes.io/warn=privileged
          - --overwrite
      - events: [postSync]
        showlogs: true
        command: kubectl
        args:
          - apply
          - -f
          - ./tailscale/connector-exitnode.yaml
