repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: ingress-nginx
    namespace: ingress
    createNamespace: true
    chart: ingress-nginx/ingress-nginx
    wait: true
    timeout: 300
    values:
      - ./values/ingress-nginx/base.yaml

  - name: grafana
    namespace: monitoring
    chart: grafana/grafana
    values:
      - ./values/grafana/base.yaml

  - name: loki
    namespace: monitoring
    chart: grafana/loki
    values:
      - ./values/loki/base.yaml

# todo: replace this so it is removed on lifecycle
hooks:
  - events: ["prepare"]
    command: "kubectl"
    args: ["apply", "-k", "./kustomize/local-path-provisioner"]
